"""empty message

Revision ID: 62fe453e075b
Revises: dd1ecd29a7aa
Create Date: 2017-03-07 10:26:43.780022

"""

# revision identifiers, used by Alembic.
revision = '62fe453e075b'
down_revision = 'dd1ecd29a7aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('obj_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'obj_type')
    ### end Alembic commands ###
