"""empty message

Revision ID: dd1ecd29a7aa
Revises: f0389471ca9e
Create Date: 2017-02-13 13:04:18.399217

"""

# revision identifiers, used by Alembic.
revision = 'dd1ecd29a7aa'
down_revision = 'f0389471ca9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('additional_tags', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'additional_tags')
    ### end Alembic commands ###
