"""empty message

Revision ID: f0389471ca9e
Revises: None
Create Date: 2016-12-02 12:28:52.110097

"""

# revision identifiers, used by Alembic.
revision = 'f0389471ca9e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('sanity_test', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('string', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('string')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('obj_id', sa.String(), nullable=True),
    sa.Column('previous_knowledge', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['obj_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obj_tags',
    sa.Column('obj_id', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['obj_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.string'], )
    )
    op.create_table('judgement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['eval_id'], ['evaluation.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.string'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judgement')
    op.drop_table('obj_tags')
    op.drop_table('evaluation')
    op.drop_table('users')
    op.drop_table('tag')
    op.drop_table('object')
    ### end Alembic commands ###
